_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 4
auto_select_gpus: False
accelerator: ddp

min_epochs: 1
max_epochs: 80

progress_bar_refresh_rate: 5

# tricks
precision: 16
accumulate_grad_batches: 1
stochastic_weight_avg: False
sync_batchnorm: True
# resume_from_checkpoint: null
