_target_: src.datamodules.isprs.PotsdamDataModule
dataset_dir:  ${data_dir}/potsdam
dataset_class: src.datamodules.datasets.isprs.ISPRSDataset

# dataset statistics
image_height: 512
image_width: 512
image_channels: 3
max_pixel: 1.0
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
# loader configuration
batch_size: 4
num_workers: 16

# dataset-specific configuration
include_dsm: false
include_ir: false

# other useful information, used by other configuration groups
num_classes: 6
class_names: ["imp_surface", "building", "low_vegetation", "tree", "car", "clutter"]
ignore_index: 255
palette:
    0: [255, 0, 0]
    1: [255, 255, 255]
    2: [0, 0, 255]
    3: [0, 255, 255]
    4: [0, 255, 0]
    5: [255, 255, 0]
    255: [0, 0, 0]
