# no _target_ since we need to manually instantiate optimizers
# since they also require the parameters from the model
_target_: torch.optim.SGD
lr: ${model.lr}
weight_decay: ${model.weight_decay}
momentum: 0.9